name = "horus"
compatibility_date = "2024-01-01"
main = "horus-gun-server.js"
compatibility_flags = ["nodejs_compat"]

[durable_objects]
bindings = [
  { name = "HORUS_GUN_ADMIN", class_name = "HorusGunAdmin" },
  { name = "HORUS_GUN_PLATFORM", class_name = "HorusGunPlatform" }
]

[[migrations]]
tag = "v1"
new_classes = ["HorusGunAdmin", "HorusGunPlatform"]